import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";
import typography from "@tailwindcss/typography";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./index.html"
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#464554",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary-container": "#3e2400",
        "tertiary-fixed": "#ffddb8",
        "on-surface-variant": "#c7c4d7",
        "on-error": "#690005",
        "primary": "#c0c1ff",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed": "#07006c",
        "surface-container-low": "#131b2e",
        "inverse-primary": "#494bd6",
        "primary-fixed": "#e1e0ff",
        "background": "#0b1326",
        "on-tertiary": "#472a00",
        "secondary-fixed-dim": "#4edea3",
        "on-primary": "#1000a9",
        "secondary-container": "#00a572",
        "on-background": "#dae2fd",
        "error": "#ffb4ab",
        "on-secondary-container": "#00311f",
        "on-surface": "#dae2fd",
        "on-secondary-fixed": "#002113",
        "inverse-surface": "#dae2fd",
        "secondary-fixed": "#6ffbbe",
        "surface-tint": "#c0c1ff",
        "outline": "#908fa0",
        "error-container": "#93000a",
        "tertiary": "#ffb95f",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#ca8100",
        "surface-container-highest": "#2d3449",
        "surface-container-high": "#222a3d",
        "inverse-on-surface": "#283044",
        "on-primary-container": "#0d0096",
        "surface-container-lowest": "#060e20",
        "on-secondary": "#003824",
        "primary-container": "#8083ff",
        "on-error-container": "#ffdad6",
        "surface-bright": "#31394d",
        "surface": "#0b1326",
        "secondary": "#4edea3",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container": "#171f33",
        "on-secondary-fixed-variant": "#005236",
        "surface-variant": "#2d3449",
        "surface-dim": "#0b1326",
        border: "rgba(255, 255, 255, 0.1)",
        input: "rgba(255, 255, 255, 0.05)",
        ring: "#c0c1ff",
        card: {
          DEFAULT: "rgba(15, 23, 42, 0.6)",
          foreground: "#dae2fd",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-xs": "4px",
        "stack-xl": "64px",
        "margin-desktop": "40px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "gutter": "24px",
        "container-max-width": "1280px",
        "stack-sm": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "display-lg-mobile": ["Sora", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "price-display": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "price-display": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(circle at center, rgba(128, 131, 255, 0.15) 0%, rgba(11, 19, 38, 0) 70%)",
      }
    },
  },
  plugins: [tailwindcssAnimate, typography],
} satisfies Config;
